using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Button = System.Windows.Controls.Button;
using Image = System.Windows.Controls.Image;
using MessageBox = System.Windows.MessageBox;
using Path = System.IO.Path;

namespace Flag_Designer
{
    /// <summary>
    /// Interaction logic for Window1.xaml
    /// </summary>
    public partial class Window1 : Window
    {
        public Window1()
        {
            InitializeComponent();

            DataContext = new CountryTagList();
        }

        public class CountryTagList
        {
            public List<string> CountryList
            {
                get
                {
                    return new List<string>
                    {
                        "ABU - Trucial States",
                        "ACE - Aceh, Sumatra",
                        "ACH - Acholi",
                        "AFG - Afghanistan",
                        "AFS - African Free State",
                        "AGJ - Angola Janga",
                        "AHU - Anhui",
                        "AIT - Ait Abbas",
                        "ALB - Albania",
                        "ALD - Algeria",
                        "ALT - Los Altos",
                        "ANH - Anhalt",
                        "ANK - Ankole",
                        "ANL - Andalusia",
                        "AOT - Aotearoa",
                        "ARA - Arabia",
                        "ARG - Argentina",
                        "ARM - Armenia",
                        "ASA - New Africa",
                        "ASH - Ashanti",
                        "ASM - Assam",
                        "ASS - Assyria",
                        "AST - Australia",
                        "AUS - Austria",
                        "AWA - Awadh",
                        "AWS - Aussa",
                        "AYM - Aymara",
                        "AZB - Azerbaijan",
                        "BAD - Baden",
                        "BAH - Bahamas",
                        "BAL - Bali",
                        "BAS - Bastar",
                        "BAV - Bavaria",
                        "BEL - Belgium",
                        "BEN - Benin",
                        "BER - Baroda",
                        "BGI - Bagirmi",
                        "BGL - Bengal",
                        "BGM - Begemder",
                        "BHI - Bahia",
                        "BHN - Bahrain",
                        "BHO - Bhopal",
                        "BHT - India",
                        "BHU - Bhutan",
                        "BIC - East India, Raj",
                        "BIK - Bikaner",
                        "BLG - Bulungan",
                        "BLH - Baluchistan",
                        "BNJ - Banjar",
                        "BNY - Bunyoro",
                        "BOH - Bohemia",
                        "BOL - Bolivia",
                        "BOR - Bornu",
                        "BOS - Bosnia-Herzegovina",
                        "BRA - Brunswick",
                        "BRD - Burundi",
                        "BRE - Bremen",
                        "BRG - Borgu",
                        "BRI - Brittany",
                        "BRN - Borana",
                        "BRU - Brunei",
                        "BRZ - Brazil",
                        "BTN - Buton",
                        "BUG - Buganda",
                        "BUK - Bukhara",
                        "BUL - Bulgaria",
                        "BUN - Bundelkhand",
                        "BUR - Burma",
                        "BYE - Belarus",
                        "BYZ - Byzantium",
                        "CAL - California",
                        "CAM - Cambodia",
                        "CAN - Canada",
                        "CAS - Castile",
                        "CAT - Catalonia",
                        "CAU - Transcaucasia",
                        "CEY - Ceylon",
                        "CHC - Chechnya, Caucasian Imamate",
                        "CHE - Cherokee",
                        "CHI - China, Great Qing",
                        "CHL - Chile",
                        "CHP - Champassak",
                        "CIR - Circassia",
                        "CLI - Carolina",
                        "CLM - Colombia, New Granada",
                        "CMI - Chiang Mai",
                        "CNW - Cornwall",
                        "COB - Saxe-Coburg-Gotha",
                        "COL - Columbia",
                        "CON - Constantine",
                        "COR - Corsica",
                        "COS - Costa Rica",
                        "CRE - Crete",
                        "CRI - Crimea",
                        "CRO - Croatia",
                        "CSA - Confederate States of America",
                        "CTR - Santa Catarina, Catharinense",
                        "CUB - Cuba",
                        "CYP - Cyprus",
                        "CZH - Czechoslovakia",
                        "DAG - Dagestan",
                        "DAH - Dahomey",
                        "DAI - Dai Nam",
                        "DEI - East Indies",
                        "DEN - Denmark",
                        "DES - Deseret",
                        "DRF - Darfur",
                        "DOM - Santo Domingo",
                        "DON - Don Cossack Host",
                        "DZG - Danzig",
                        "ECU - Ecuador",
                        "EGY - Egypt",
                        "ELS - El Salvador",
                        "ENG - England",
                        "EOT - Emirate of Transjordan",
                        "EQT - Confederation of the Equator",
                        "EST - Estonia",
                        "ETH - Ethiopia",
                        "EZO - Ezo",
                        "FER - Kamchatka",
                        "FIN - Finland",
                        "FLA - Flanders",
                        "FLR - Florida",
                        "FND - Federation of the Andes",
                        "FRA - France",
                        "FRM - Frankfurt",
                        "FRS - Formosa",
                        "FSA - Free States of America",
                        "FTJ - Futa Jallon",
                        "FTR - Futa Toro",
                        "GAL - Galicia-Lodomeria",
                        "GBR - Great Britain",
                        "GCO - Gran Colombia",
                        "GEO - Georgia",
                        "GER - Germany",
                        "GJM - Gojjam",
                        "GLD - Geledi",
                        "GLI - Galicia",
                        "GNG - Da Cheng",
                        "GRE - Greece",
                        "GRG - Georgia",
                        "GRI - Guarani",
                        "GRN - Greenland",
                        "GUA - Guatemala",
                        "GUI - Guizhou",
                        "GWA - Gwalior",
                        "GZA - Gaza",
                        "HAI - Haiti",
                        "HAM - Hamburg",
                        "HAN - Hanover",
                        "HAR - Harar",
                        "HAU - Gobir",
                        "HAW - Hawaii",
                        "HBC - Hudson Bay Company",
                        "HDJ - Hedjaz",
                        "HEK - Hesse-Kassel",
                        "HES - Hesse",
                        "HNA - Hunan",
                        "HND - India",
                        "HOB - Hobyo",
                        "HOH - Hohenzollern",
                        "HOL - Holstein",
                        "HON - Honduras",
                        "HRE - Central Europe, Holy Roman Empire",
                        "HTH - Hathawaddy",
                        "HUN - Hungary",
                        "HYD - Hyderabad",
                        "HZJ - Hazarajat",
                        "IBE - Iberia",
                        "ICL - Iceland",
                        "IDN - Indonesia, Majapahit",
                        "IND - Indore",
                        "ION - Ionian Islands",
                        "IQU - Iquicha",
                        "IRE - Ireland",
                        "IRO - Haudenosaunee",
                        "IRQ - Iraq",
                        "ISQ - Isaaq",
                        "ISR - Israel",
                        "ITA - Italy",
                        "IUS - Kazan",
                        "JAB - Jabal Shammar",
                        "JAI - Jaipur",
                        "JAM - Jamaica",
                        "JAN - Jan Mayen",
                        "JAP - Japan",
                        "JAS - Jaisalmer",
                        "JAV - Java",
                        "JMB - Jambi, Sumatra",
                        "JOD - Jodhpur",
                        "JOH - Johore",
                        "KAL - Kalat",
                        "KAS - Kashmir",
                        "KAT - Kathiri",
                        "KAU - Kaurna",
                        "KAZ - Kazakhstan",
                        "KFA - Kaffa",
                        "KHI - Khiva",
                        "KHM - Khmu",
                        "KHN - Kachin",
                        "KLM - Kalmykia",
                        "KLT - Kalimantan",
                        "KOK - Kokand",
                        "KON - Kongo",
                        "KOR - Korea, Joseon",
                        "KRA - Krakow",
                        "KRG - Karagwe",
                        "KRN - Karen",
                        "KRT - Kaarta",
                        "KTI - Kutai, Kalimantan",
                        "KUK - Danubian State",
                        "KUR - Kurdistan",
                        "KUT - Kutch",
                        "KZH - Kishi Zhuz",
                        "LAD - Ladakh",
                        "LAH - Lahej",
                        "LAN - Lanfang",
                        "LAO - Laos",
                        "LAT - Latvia",
                        "LEB - Lebanon",
                        "LIB - Liberia",
                        "LIP - Lippe",
                        "LIT - Lithuania",
                        "LOM - Lombardia",
                        "LOU - Louisiana",
                        "LUA - Luang Prabang",
                        "LUB - Lübeck",
                        "LUC - Lucca",
                        "LUX - Luxembourg",
                        "MAD - Madagascar, Merina Kingdom",
                        "MAH - Mahra",
                        "MAK - Makran",
                        "MAL - Mali",
                        "MAS - Mascara",
                        "MAY - Maya",
                        "MCH - Manchuria",
                        "MEC - Mecklenburg",
                        "MEI - Saxe-Meinengen",
                        "MEW - Mewar",
                        "MEX - Mexico",
                        "MGB - Maghreb",
                        "MGD - Maguindanao",
                        "MGL - Mongolia",
                        "MJT - Majerteen",
                        "MKT - Miskita",
                        "MLT - Malta",
                        "MNG - Minas Gerias",
                        "MNP - Manipur",
                        "MOD - Modena",
                        "MOL - Moldavia, Moldova",
                        "MON - Montenegro",
                        "MOR - Morocco",
                        "MSN - Massina",
                        "MST - Mecklenburg-Strelitz",
                        "MTC - Métis",
                        "MUG - Hindustan",
                        "MUI - Muisca",
                        "NAG - Nagpur",
                        "NAH - Aahuac",
                        "NAL - Natalia",
                        "NAS - Nassau",
                        "NAV - Navarra",
                        "NBS - New Brunswick",
                        "NCA - Mountain Republic",
                        "NCR - North Carolina",
                        "NEJ - Nejd",
                        "NEN - New England",
                        "NET - Netherlands",
                        "NEW - Newfoundland",
                        "NGF - North German Federation",
                        "NIC - Nicaragua",
                        "NNV - Nunavut",
                        "NOR - Norway",
                        "NPU - North Peru",
                        "NPU - South Peru",
                        "NSW - New South Wales",
                        "NVS - Nova Scotia",
                        "NZL - New Zealand",
                        "OCC - Occitania",
                        "OLD - Oldenburg",
                        "OMA - Oman",
                        "ONT - Ontario, Upper Canada",
                        "ORA - Oranje",
                        "ORG - Oregon, Columbia District",
                        "ORI - Orissa",
                        "OYO - Oyo",
                        "OZH - Orta Zhuz",
                        "PAK - Pakistan",
                        "PAL - Palestine",
                        "PAN - Punjab",
                        "PAP - Rome, Papal States, Roman Republic",
                        "PAR - Parma",
                        "PAU - Paulistânia",
                        "PBC - Peru-Bolivia",
                        "PCO - Puerto Rico",
                        "PER - Persia",
                        "PEU - Peru",
                        "PHI - Philippines",
                        "PLC - Poland-Lithuania, Commonwealth",
                        "PLT - Rio de la Plata",
                        "PLY - Tahiti",
                        "PNI - Piratini, Riograndense",
                        "PNM - Panama",
                        "PNS - Polynesia",
                        "POL - Poland",
                        "POM - Pomerania",
                        "PON - Pontianak",
                        "POR - Portugal",
                        "PRA - Grão-Pará",
                        "PRC - Paris Commune",
                        "PRG - Paraguay",
                        "PRK - Perak",
                        "PRM - Perm",
                        "PRU - Prussia",
                        "PUE - Pueblo",
                        "QIA - Qian",
                        "QUE - Qeubec, Lower Canada",
                        "RHE - Rhineland",
                        "RHN - Confederation of the Rhine",
                        "RIO - Río Grande",
                        "ROM - Romania",
                        "RSM - San Marco",
                        "RUS - Russia, Soviet Union",
                        "RWD - Rwanda",
                        "SAF - South Africa, Cape Colony",
                        "SAK - Siak",
                        "SAR - Sardinia-Piedmont",
                        "SAS - South Australia",
                        "SAV - Savoy",
                        "SAX - Saxony",
                        "SCA - Scandinavia",
                        "SCH - Schleswig-Holstein",
                        "SCM - Schaumburg-Lippe",
                        "SCN - Scania",
                        "SCO - Scotland",
                        "SCR - South Carolina",
                        "SCW - Schwarzburg",
                        "SDM - Sidamo",
                        "SEL - Selangor",
                        "SEQ - Indian Territory, Seqouyah",
                        "SER - Serbia",
                        "SGF - South German Federation",
                        "SGU - Segou",
                        "SHA - Shandong",
                        "SHN - Shanxi",
                        "SHW - Shewa",
                        "SIA - Siam",
                        "SIB - Siberia",
                        "SIC - Two Sicilies",
                        "SIH - Sichuan",
                        "SIK - Sikkim",
                        "SIL - Sierra Leone",
                        "SIN - Sindh",
                        "SLO - Slovenia",
                        "SLV - Slovakia",
                        "SMB - Sambas, Kalimantan",
                        "SMI - Sapmi",
                        "SOK - Sokoto",
                        "SPA - Spain",
                        "SRB - Sorbia",
                        "SRK - Surakarta, Mataram",
                        "STG - Sintang, Kalimantan",
                        "SUD - Sudan, Funj, Mahdist State",
                        "SUL - Sulu",
                        "SWE - Sweden",
                        "SWI - Switzerland",
                        "SYR - Syria",
                        "TAS - Tasmania, Van Dieman's Land",
                        "TEX - Texas",
                        "TGR - Tigray",
                        "TIB - Tibet",
                        "TID - Tidore",
                        "TIS - Turtle Island",
                        "TNS - Tungus",
                        "TOB - Toba",
                        "TPG - Heavenly Kingdom",
                        "TRA - Travancore",
                        "TRC - Turkmenia",
                        "TRE - Trieste",
                        "TRH - Turekestan",
                        "TRI - Tripolitania",
                        "TRN - Transvaal",
                        "TRS - Transylvania",
                        "TUG - Touggourt",
                        "TUN - Tunis",
                        "TUR - Turkey, Ottoman Empire",
                        "TUS - Tuscany",
                        "TUV - Tuva",
                        "TWT - Tawantinsuyu",
                        "UBD - United Balkan Provinces",
                        "UCA - Central America",
                        "ULS - Ulster",
                        "UNL - United Netherlands, Burgundy",
                        "UNT - United Tribes",
                        "UOM - Michigan",
                        "URU - Uruguay",
                        "USA - United States of America",
                        "UZH - Uly Zhuz",
                        "VEN - Venice",
                        "VIE - Vientiane",
                        "VNZ - Venezuela",
                        "WAD - Wadai",
                        "WAL - Wallachia",
                        "WAS - Western Australia",
                        "WEI - Saxe-Weimar",
                        "WES - Westphalia",
                        "WIN - West Indies",
                        "WLD - Waldeck",
                        "WLG - Welega",
                        "WLL - Wallonia",
                        "WLO - Wello",
                        "WLS - Wales",
                        "WSG - Warsangali",
                        "WUR - Württemberg",
                        "XIB - Xibei",
                        "XIN - Uyghuristan",
                        "YAK - Yakutia",
                        "YEM - Yemen",
                        "YOG - Yogyakarta, Mataram",
                        "YUC - Yucatán",
                        "YUE - Yue",
                        "YUG - Yugoslavia",
                        "YUN - Yunnan",
                        "YUZ - Yuanzhumin",
                        "ZAI - Azal, Qasimid State",
                        "ZAN - Zanzibar",
                        "ZHI - Zhili",
                        "ZIM - Zimbabwe",
                        "ZND - Azande",
                        "ZUL - Zulu"
                    };
                }
            }

        }

    }
}
